version: "3.9"

services:

  ###################################################
  #   1) CEREBRO - Full cluster GUI management
  ###################################################
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    network_mode: host
    environment:
      CEREBRO_SSL_VERIFY: "false"
      CEREBRO_DEFAULT_USERNAME: "elastic"
      CEREBRO_DEFAULT_PASSWORD: "Sanem001@"
    restart: unless-stopped
